# Generated by Django 5.1 on 2024-08-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_blog_category_alter_blog_meta_alter_blog_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
