# Generated by Django 5.1 on 2024-09-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='favorited_by',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blogimage',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='P_favorited',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='user',
        ),
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
