# Generated by Django 5.1 on 2024-09-10 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_blog_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='expiry',
        ),
    ]
